### ISSUE TITLE
Package @zenfs/emscripten not found on npm

### ISSUE THREAD

**Issue by adamziel** [zen-fs/emscripten#1]
I don't think the package has been published:

https://www.npmjs.com/package/@zenfs/emscripten

Also, the source files in the repo are empty.

**Comment by james-pre** [comment]
@adamziel, I'm still waiting on [DefinitelyTyped#69218](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69218), however I have done some preliminary work. Once the PR is merged I expect the Emscripten backend to be released within a week or two.

**Comment by james-pre** [comment]
[v0.0.1](https://github.com/zen-fs/emscripten/releases/tag/v0.0.1) is out! Expect it to be unstable.
